name: image_merger_dart
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  sprintf: ^7.0.0
  json_annotation: ^4.8.1
  rxdart: ^0.27.7
  path_provider: ^2.1.1
  tuple: ^2.0.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  pretty_json: ^2.0.0
  dynamic_color: ^1.6.8
  flutter_spinkit: ^5.2.0
  image_picker: ^1.0.4
  permission_handler: ^11.1.0
  logger: ^2.0.2+1
  images_picker: ^1.2.11
  bot_toast: ^4.1.3
  url_launcher: ^6.2.1
  carousel_slider: ^4.2.1
  starrail_ui:
    git:
      url: https://github.com/ArchangelXu/Starrail-Flutter-UI-kit
      path: library
      ref: master
  device_info_plus: ^9.1.1
  image_size_getter: ^2.1.2
  uuid: ^4.2.1
  image: ^4.1.3
  collection: ^1.18.0
  file_picker: ^6.1.1
  qr_flutter: ^4.1.0
  pasteboard: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: any

flutter:

  uses-material-design: true

  assets:
    - assets/images/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  windows:
    generate: true
  macos:
    generate: true
  image_path: "assets/images/launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
